spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 761567995259-oc2fobljc2ga52nkqfje7tn1otfg5vi1.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth
    username: postgres
    password: l8n3_a7-c2.E
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update