spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 761567995259-br4rpp47cevcvhmpg6fcrevmgk480g7s.apps.googleusercontent.com
            client-secret: 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
            scope: profile,email
  datasource:
    url: jdbc:postgresql://localhost:5432/oauth
    username: postgres
    password: l8n3_a7-c2.E
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update